### PR TITLE
isRunning misbehaved on nodes inside parallel

### PR DESCRIPTION
**Pull request by jglick**
Regression from #19.

Without fix, would fail with

```
[test0 #1] java.lang.IllegalStateException: cannot start writing logs to a finished node org.jenkinsci.plugins.workflow.cps.nodes.StepStartNode[id=9]
[test0 #1] 	at org.jenkinsci.plugins.workflow.support.actions.LogActionImpl.<init>(LogActionImpl.java:110)
[test0 #1] 	at org.jenkinsci.plugins.workflow.support.actions.LogActionImpl.stream(LogActionImpl.java:81)
[test0 #1] 	at org.jenkinsci.plugins.workflow.support.DefaultStepContext.get(DefaultStepContext.java:73)
[test0 #1] 	at org.jenkinsci.plugins.workflow.support.actions.LogActionImplTest$ChattyStep$Execution.run(LogActionImplTest.java:100)
[test0 #1] 	at org.jenkinsci.plugins.workflow.support.actions.LogActionImplTest$ChattyStep$Execution.access$100(LogActionImplTest.java:75)
[test0 #1] 	at org.jenkinsci.plugins.workflow.support.actions.LogActionImplTest$ChattyStep$Execution$Callback.onSuccess(LogActionImplTest.java:108)
[test0 #1] 	at …
```

Regarding #19, if you disable the assertion and just use `FlowNode.isRunning`, the test case would fail looking for

    logging from LBBL with 0 commands to go

@reviewbybees esp. @svanoort

### CODE REVIEW

**Comment by svanoort** [comment]
🐝  with full understanding.  Only one of the currentHeads is inspected with LinearScanners

**Comment by jglick** [comment]
I have a patch under preparation to make that apparent.

**Comment by jglick** [comment]
Will work on a local test case for this which exercises all the known use cases. In the meantime I need this released.

**Comment by svanoort** [comment]
@jglick Could you use a lightly modified version of what I have in pipeline-graph-analysis:  https://github.com/jenkinsci/pipeline-graph-analysis-plugin/blob/master/src/test/java/org/jenkinsci/plugins/workflow/pipelinegraphanalysis/StatusAndTimingTest.java#L319  

I am testing very similar logic there.

**Comment by jglick** [comment]
No, my needs here are rather different.

Test case almost ready, just doing some polishing.

**Comment by svanoort** [comment]
Looks reasonable, waiting for CI though

**Comment by jglick** [comment]
CI build passed, not sure why it did not update.

**Pull request merged**
