### PR TITLE
Add localization for Chinese

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
@jenkinsci/code-reviewers Anyone can help me to review this PR, thanks!

**Comment by LinuxSuRen** [comment]
@rsandell Sorry about this, I already fixes.

**Comment by LinuxSuRen** [comment]
@jenkinsci/chinese-localization-sig Please help to review.

**Comment by dwnusbaum** [comment]
@LinuxSuRen Do you still want us to merge+release this, or should it go straight into https://github.com/jenkinsci/localization-zh-cn-plugin?

**Comment by LinuxSuRen** [comment]
It's been a long time. I'll move this to localization plugin. Thanks for your tips.
@dwnusbaum

**Comment by LinuxSuRen** [comment]
See also jenkinsci/localization-zh-cn-plugin/pull/37

**Comment by dwnusbaum** [comment]
Thanks!

**Pull request closed without merging**
