### PR TITLE
[JENKINS-52001] - Enable Incrementals deployment for the Java 10 support branch

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Built on the top of #65 

Requires https://github.com/jenkins-infra/pipeline-library/pull/68 to be merged

@jenkinsci/java10-support

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
"Skipping deployment as no artifacts were found with the expected path, typically due to a PR merge build not up to date with its base branch". But the branch is based on the master...

No idea what's going on. @jglick I would appreciate an advice

**Comment by jglick** [comment]
Exactly what it says. This PR was not up to date with its base branch. So Jenkins built an ephemeral merge commit, which will not be deployed.

**Comment by oleg-nenashev** [comment]
@jglick Thanks! My `origin` was just pointing to the wrong repo 🤦‍♂️

**Comment by svanoort** [comment]
@oleg-nenashev Merging but I want to follow up and address this to solve the unit tests woes

**Pull request merged**
