### PR TITLE
[JENKINS-52007] - Plugin POM 3.28: Update Animal Sniffer and other Maven plugins towards Java 11 support

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Downstream of:

* https://github.com/jenkinsci/plugin-pom/pull/114
* https://github.com/mojohaus/animal-sniffer/pull/50

We need a release of Animal Sniffer to integrate it, but no hurry

CC @ndeloof @olamy @svanoort

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
CC @jenkinsci/java11-support . Updated Plugin POM to pick up related fixes towards Java 11 support there

**Comment by batmat** [comment]
```
windows] [ERROR] Failed to execute goal on project workflow-support: Could not resolve dependencies for project org.jenkins-ci.plugins.workflow:workflow-support:hpi:2.19-rc293.067e6ad8d972: Could not find artifact net.java.sezpoz:sezpoz:jar:1.13-java10-SNAPSHOT in azure (https://repo.azure.jenkins.io/public/) -> [Help 1]

[windows] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project workflow-support: Could not resolve dependencies for project org.jenkins-ci.plugins.workflow:workflow-support:hpi:2.19-rc293.067e6ad8d972: Could not find artifact net.java.sezpoz:sezpoz:jar:1.13-java10-SNAPSHOT in azure (https://repo.azure.jenkins.io/public/)
```

Weird, not sure where sezpoz snapshot is coming from yet.

**Comment by oleg-nenashev** [comment]
No idea as well. Will park it for now

**Comment by dwnusbaum** [comment]
`master` is already [using parent pom 3.32](https://github.com/jenkinsci/workflow-support-plugin/blob/1c5f1c69a140e289293aff19ad0e8586e96d59d4/pom.xml#L31), and I don't think the animal-sniffer exclusion is necessary anymore. I will go ahead and close this, but please reopen it if I am misunderstanding something and the PR is still needed.

**Pull request closed without merging**
